# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import maps.validators


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[maps.validators.validate_location]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[maps.validators.validate_title]),
        ),
    ]
