# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20170908_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
